### ISSUE TITLE
1-AsteroidBlaster Occasionally clicking the lower of 2 astroids makes both explode

### ISSUE THREAD

**Issue by TyrfingMjolnir** [JohnSundell/ImagineEngine#10]
This only occurs at a certain distance between the two and the top one not yet being displayed, not able to reproduce on purpose but happens occasionally.

**Comment by JohnSundell** [comment]
Thanks for this bug rapport @TyrfingMjolnir! I would really appreciate any more concrete reproduction steps if you can find them, like where the asteroids were in the scene, anything else you observed?  I'll try to reproduce this myself and see if I encounter the same bug.

**Comment by JohnSundell** [comment]
Interesting, thanks, I'll look into it 👍

**Comment by palleraccio** [comment]
Hi,
I had the same issue, but I noticed that it happens also when both actors are displayed. 
I'm able to reproduce often the issue: indeed, it happens when two asteroids are close each other and the tap is pretty close to each asteroid. I've printed an example of positions of actors and tap when the issue happened:
```
Tap {point=(329.5, 155.5)}
Asteroid {position=(278.0, 126.683801412582), rect=(240.5, 91.1838014125824, 75.0, 71.0)
Asteroid {position=(335.0, 224.990004301071), rect=(297.5, 189.490004301071, 75.0, 71.0)
```

**Comment by JohnSundell** [comment]
Thanks @palleraccio, that is really useful debug info 👍 The problem was that two asteroids actually could have their frames overlap, which would trigger the `clicked` event on both of them when the player tapped at an overlapped point 😅 Increased the duration between asteroids to 2 seconds in the tutorial to fix it: https://github.com/JohnSundell/ImagineEngine/pull/17

Thanks a lot both @palleraccio & @TyrfingMjolnir for identifying and helping to resolve this issue 🎉
