### ISSUE TITLE
consider to open a Slack channel

### ISSUE THREAD

**Issue by AnotherCoolDude** [JohnSundell/ImagineEngine#116]
Hey there,

awesome Project, love it so far. Since development happens pretty fast, i recommend using Slack (or an alternative) for faster communication. It has already been proven helpful in other projects (take a look at Vapor for example). It is also a great platform for sharing ideas and providing help.

**Comment by JohnSundell** [comment]
Hi @AnotherCoolDude! 👋 

Happy to hear that you like Imagine Engine 😄 

I've been thinking a lot about that actually (in fact, I already have a Slack registered for Imagine Engine, but no invites sent out). However I've decided (for now) not to use it for these reasons:

1. I don't have time to maintain another communication channel (I try to limit my social channels as much as I can in order to be able to be responsive and help out people as much as possible across all of my projects).
2. It would create a divide of information. The beauty of using only GitHub is that *everything* is here. With Slack, the risk (which I've seen happen) is that lots of context would only be available in the chat history of Slack, which would make it harder for people to keep up with the project. There's already a bit of a problem that a lot of people ping me directly on Twitter for support, but I always redirect them here in order to have everything in one place and to start building up a "knowledge bank" in the community.
3. We are very open to questions and support here on GitHub. Anyone is super welcome to open an issue if they need help or want to discuss a game idea, and that's already happening quite a lot.

So for those reasons Slack won't happen right now, but maybe in the future as the project evolves and its needs change. Thanks a lot for the suggestion and keep 'em coming 👍
