### ISSUE TITLE
Tutorial build errors on Xcode 8.3.3

### ISSUE THREAD

**Issue by magnusviri** [JohnSundell/ImagineEngine#12]
Downloaded and tried to build the Tutorial and I get errors: 

“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

warning: no umbrella header found for target 'ImagineEngine-iOS', module map will not be generated

I tried what it suggested but it didn't fix it.  It's been a long time since I've used Xcode so I'm not exactly sure what to do about it.

I'm using Xcode 8.3.3 on Mac OS X 10.12.6.

**Comment by JohnSundell** [comment]
Hi @magnusviri 👋

Imagine Engine is written in Swift 4, which means that you need to update to Xcode 9.0 or later in order to compile it. Basically anytime you get an error like that it's usually because your Xcode's Swift version is too low. Get the latest version of Xcode from the App Store and you should be ready to go 😄

Let me know if you still encounter errors after updating Xcode. Closing this one for now.
