### ISSUE TITLE
Dialogue Plugin

### ISSUE THREAD

**Issue by Alex88WH** [JohnSundell/ImagineEngine#139]
Hey there! I'm trying to create a plugin that handles dialogues. I could use some help :D
The final goal is a plugin that can be added on any kinda games. Something simple like a sign in a village or even a complex dialogue with characters.

I’ve two games (dialogue system or something like that) in mind: 

**Fire Emblem Heroes** 
![uspiuus](https://user-images.githubusercontent.com/8467996/34846422-4f70cb12-f6ff-11e7-8bc7-cbd6596cfaf3.png)
- Traditional RPG style (character is showed while talking)
- 	Character animation (the character usually changes his pose/posture/sprite)

**Undertale**
<img width="200" alt="screen shot 2018-01-11 at 18 24 13" src="https://user-images.githubusercontent.com/8467996/34846346-01ee4ebe-f6ff-11e7-8aaa-7d6ff7fec6ee.png">
- 	Simple 
- 	Animated words (single and all the text) (Label supports animation now o/)

I tried to play with those in mind on a Playground. What I got so far:
- Reading a local JSON (Text, Character (name), Animation (Character sprite))
- 	Update method that call the next item in array (JSON). Everything is working so far. 

<img width="300" alt="screen shot 2018-01-11 at 16 58 23" src="https://user-images.githubusercontent.com/8467996/34847438-7ccadadc-f702-11e7-82ba-8b2ef91b3069.png">
<img width="200" alt="screen shot 2018-01-11 at 18 49 38" src="https://user-images.githubusercontent.com/8467996/34847443-82e9f466-f702-11e7-8e16-dd5dfd92b8b7.png">(Raven of Fire Emblem. Testing)

Next: 
- Multiline (I was using \n on JSON haha) (**HIGH PRIORITY!**)
- 	Simple animations (Label and Actor already got a lot what I need like fade out/in and so on)
- 	Typing effect (as an option)
- 	Adapt the plugin to be either simple (only a box n text), normal (name + dialogue) and dialogue (character sprite) and for any screen size

This is it! I’m a beginner and I don’t know if I can create something like that using clean and elegant code or best practices at all (But I’m learning. Reading Imagine Engine is helping me a lot). I could use some direction or tips. Thanks and sorry for all English mistake :D

**Comment by JohnSundell** [comment]
@Alex88WH Wow that looks really cool! 😄 I think a plugin like that could be of great value to the community since creating these kinds of dialogs is very common in many different kinds of games.

For multiline, the good news is that it's quite easy to add support for it. `CATextLayer` (which `Label` uses for rendering) has a `isWrapped` property that if set to true auto-wraps the text within the layer's bounds. So all we really need to do is expose that as part of the `Label` API and it should just work. Did a quick hack and here's what it looks like with `isWrapped = true`:

![screen shot 2018-01-11 at 23 06 04](https://user-images.githubusercontent.com/2466701/34849937-4d738a5a-f724-11e7-86ae-47b1005190d6.png)

As for a typing effect, one way to solve that would be to create an `Action` that changes the label's `text` property by adding one character at a time after a certain interval. That should generate that type of type-writer effect which is normally seen in RPGs etc.

Let me know what you think of the above 😄 Also if @insidegui, @mattiashagstrand or anyone else have any ideas then feel free to pitch in 😉

**Comment by Alex88WH** [comment]
That's awesome!! Working here, thanks! 🎉 I'll post more progress later on ✌︎
![jan-12-2018 11-24-50](https://user-images.githubusercontent.com/8467996/34877023-5ad3b5b4-f78b-11e7-98fa-177f084fc6c1.gif)
(shouldAutoResize as false!)

**Comment by JohnSundell** [comment]
Awesome! Added issue #142 to add support for line wrapping to `Label` 👍

**Comment by mattiashagstrand** [comment]
Very nice!

To allow for even more text effects we could make Label `Rotatable` and `Scalable` as well.
Shouldn't be to hard or what do you think @JohnSundell?

**Comment by JohnSundell** [comment]
@mattiashagstrand Sounds like a plan! 👍

**Comment by JohnSundell** [comment]
@mattiashagstrand Created issues #152 & #153 for scaling & rotation for labels, think they can be great starter tasks 😄

**Comment by JohnSundell** [comment]
@Alex88WH Do you think you need more engine changes to implement your plugin? It looks like you're good to go, right?

**Comment by Alex88WH** [comment]
Yep! I'm working on it! Gonna close this issue. Thank you all 🤩 (I'll post updates and the plugin itself when I finish it (or at least make it viable to use))
