### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by SwiftStudies** [JohnSundell/ImagineEngine#154]
This is absolutely an enhancement request, but having support for using Swift Package Manager would be great.

**Comment by JohnSundell** [comment]
Sounds like a great idea @SwiftStudies 👍

**Comment by freak4pc** [comment]
@SwiftStudies To the best of my knowledge, SPM as of today doesn't support UIKit, AppKit, etc so you probably won't be able to ship this library with it.

**Comment by JohnSundell** [comment]
You can actually link against AppKit in a Swift Package, no problems (not UIKit, since SPM doesn't support iOS yet). But the bigger problem is that you can't include any resources in a SPM program, which means you'd either have to rely on downloading textures and sounds over the network at runtime, or only use code-generated assets. So SPM is not very practical for game development in its current state, but it would still be nice to support it for the future 🙂

**Comment by JohnSundell** [comment]
Think I'll close this one for now, since SPM is not practical for using Imagine Engine at the moment. We can revisit it in the future when you can bundle resources in a Swift package.
