### ISSUE TITLE
Support JPG-based textures

### ISSUE THREAD

**Issue by JohnSundell** [JohnSundell/ImagineEngine#19]
Currently, Imagine Engine only supports loading texture images in the PNG format, but it would be very nice to support JPG as well. Suggested implementation is to add a `Format` enum to `Texture`, that lets the user specify the format, and then in `TextureManager` read that format and decide the file extension based on it.

**Comment by aranasaurus** [comment]
I started on this last night, but didn't really like where I ended up with it because I didn't have a good way to test it. It looks like `TextureManager` and friends got a few updates since I looked at it too, so I ended up just scrapping it.

I think this task needs better tests around the stuff that's already there in order to be a "good first issue", because it kind of felt like making changes in the void. 

I may take this back up later today, but I was kind of hoping to get some guidance on how to write said tests, or should I just create my own sample project and test it in there separately? I guess that's another thing that would be nice to have, some kind of sample app bundled in to the repo that demonstrates all the things. 🤔

**Comment by JohnSundell** [comment]
Yeah a sample app would be very nice - it would also be something we could run UI tests against to make sure that things like click handling and rendering works end-to-end 👍

To be able to test this, I suggest bundling just a blank JPG file in the test bundle, then injecting the test `Bundle` into `BundleTextureImageLoader`, like this:

```swift
let bundle = Bundle(for: type(of: self))
let imageLoader = BundleTextureImageLoader(bundle: bundle)
let textureManager = TextureManager(imageLoader: imageLoader)
```

I agree that it's a bit too in-depth to be a starter task though, so I'll remove `good first issue`. Let me know if you want any more details or want to discuss some potential solution. Maybe @dymv has some ideas too? 😄

**Comment by dymv** [comment]
Hey folks, regarding testing I totally agree with @JohnSundell about adding blank JPG file, it must  be the simplest way of achieving testability (perhaps we could abstract `Bundle` and hide it behind a protocol, and capture passed parameters, but it is unnecessary complication here 😜). 

Another thing here is how we would propagate this change to `Animation`, `Block` and other places where we can find the pattern of accepting only `spriteSheetNamed`(or variations) parameter without explicit `format` parameter. Do we want to add one more parameter to such constructors? Or create a struct that will contain all required information for loading particular texture (name, scale, format, ...)?

I would go with 2nd option, I probably can try to come up with some PR later on. Let me know if you have any ideas on this. 😃

**Comment by JohnSundell** [comment]
Actually, it might lead to simpler test code by doing what you're suggesting about mocking `Bundle` @dymv - since if we use a bundled image we'd have to find a way to get to the actual image being rendered to be able to perform an assertion. It *could* be done by using `@testable import` and asserting against the `contents` of an actor's `layer`, but that feels like relying too much on implementation details.

About the API, I think that `Texture` should hold information about the format, and then as you say we can add a `format` parameter to all the methods that don't accept a `Texture`, but instead a name. We can use a default argument to make `.png` the default, so that we don't make the API more complicated to use.
