### ISSUE TITLE
Add code style guidelines, perhaps with an automated linter

### ISSUE THREAD

**Issue by aranasaurus** [JohnSundell/ImagineEngine#33]
So @JohnSundell doesn't have to do commits like [this](https://github.com/JohnSundell/ImagineEngine/commit/50ed860f732485d3d6b7ab6d768daf3afa27bb17) anymore :)

**Comment by JohnSundell** [comment]
Haha both you and @dymv picked up on that commit 😅 So I'm totally all for a linter, perhaps [SwiftLint](https://github.com/realm/SwiftLint)? I've used it in a few other projects, and it's very nice & highly configurable 👍

The reason I made that commit (rather than giving you direct feedback on the PRs) is that I don't want the first contributor experience to involve lots of round trips with comments about nitpicky details that don't actually affect the functionality. I still like to fix these things, but it's something that can be totally done post-merge. Basically I didn't want to bother you with these things, since it's something you usually "grow into" when contributing more to the same project. 🙂

But yeah, let's add a linter so that the feedback will be direct and automatic (and can also be run locally before even making a PR if desired).

**Comment by aranasaurus** [comment]
> The reason I made that commit (rather than giving you direct feedback on the PRs) is that ...

I totally understand, and that's why I made the issue; a linter should be responsible for taking care of all that so you don't have to feel nitpicky but the code can stay consistently styled and beautiful without a lot of back and forth on PRs :)

**Comment by JohnSundell** [comment]
Yeah totally agree 👍
