### ISSUE TITLE
Change Size of Actor

### ISSUE THREAD

**Issue by alisandagdelen** [JohnSundell/ImagineEngine#36]
Hi, i read the first tutorial and then try to make something different.
I find some different assets and it was bigger than first tutorial's resources.
So i tried this
`let enemy = Actor(size: Size(width: 0.5, height: 0.5))`
`enemy.animation = Animation(name: "Enemies", frameCount: 8, frameDuration: 0.02)`
so it did not change the size of Actor. Also i tried to set size after initialization of actor and animation like
`enemy.size = Size(width: 0.5, height: 0.5)`
And again did not change the size.

When i tried to set scale
```
enemy.scale = 0.3
enemy.hitboxSize!.height = enemy.size.height * 0.3
enemy.hitboxSize!.width = enemy.size.width * 0.3
```
it works to change size of image but hit boxes were same size of orginal image size.

**Comment by JohnSundell** [comment]
Hi @alisandagdelen and welcome to the project! 👋

So there's a couple of things at play here (no pun intended 😅). First, Imagine Engine automatically resizes an actor when it plays an animation, per default. So your `enemy` actor will be automatically sized according to the textures of your animation. So setting its size manually won't have any effect. You can turn this off by setting `autoResize` to `false` on your animation.

Next, an actor first gets sized when it gets added to a scene. The reason for this is because (for better performance) we want to load all textures on the scene-level, to enable caching and things like that.

Finally, @aranasaurus just made a patch the other day to fix that hit boxes weren't scaled according to an actor's scale. So if you upgrade to Imagine Engine 0.4.0 that should be resolved.

Hope the above makes things a bit more clear (I'll be working a lot on adding more documentation over the next couple of weeks), and let me know if there's anything else I/we can help out with 😄

**Comment by JohnSundell** [comment]
@alisandagdelen Let us know if there's anything else we can help with or if this issue can be closed 🙂

**Comment by alisandagdelen** [comment]
@JohnSundell Oh sorry i just saw notifications :) Thanks for your help :)

**Comment by JohnSundell** [comment]
No problems 🙂
