### ISSUE TITLE
module file was created for incompatible target x86_64-apple-macosx10.12

### ISSUE THREAD

**Issue by TyrfingMjolnir** [JohnSundell/ImagineEngine#9]
Playground execution failed:

error: Playground.playground:3:8: error: module file was created for incompatible target x86_64-apple-macosx10.12: /Users/user/Library/Developer/Xcode/DerivedData/AsteroidBlaster-cxopjqrvbpqmgucxltcgjmcfwabc/Build/Products/Debug/ImagineEngine.framework/Modules/ImagineEngine.swiftmodule/x86_64.swiftmodule
import ImagineEngine
       ^

**Comment by TyrfingMjolnir** [comment]
Builds just fine for iOS on the other hand...

**Comment by JohnSundell** [comment]
Hey @TyrfingMjolnir 👋

So if I understand this issue correctly, you want to use the AsteroidBlaster playground but for Mac? Did you change the playground's platform setting to macOS before compiling Imagine Engine?

**Comment by TyrfingMjolnir** [comment]
Building this for mac works fine after building for ios, but gave the error as above when building off of a fresh git clone when building only for macos.

**Comment by JohnSundell** [comment]
Yeah, but that makes total sense if you didn't change the platform of the playground to macOS. The playground can't import the module until it has been built, and since you initially only built it for macOS but the playground is for iOS, you're gonna get an error like that. Then when you built for iOS the problem resolved because now you had a module with the correct architecture built.

Closing this one 🙂
